page-top-title: '<span data-lang="en">Zhu Zhenfang</span><span data-lang="zh">朱振方</span>'
copyright-text: '&copy; <span id="current-year">2026</span> <span data-lang="en">Zhu Zhenfang</span><span data-lang="zh">朱振方</span>'
